# Generated by Django 2.2.5 on 2019-12-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutComingTransact',
            fields=[
                ('no_transac', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=255)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.CustomUserModel')),
            ],
            options={
                'db_table': 'outcoming_transac',
            },
        ),
        migrations.CreateModel(
            name='InComingTransact',
            fields=[
                ('no_transac', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=255)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.CustomUserModel')),
            ],
            options={
                'db_table': 'incoming_transac',
            },
        ),
    ]
