# Generated by Django 2.2.5 on 2019-12-25 02:23

import Transactions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20191221_2119'),
        ('Items', '0001_initial'),
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('no_transac', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=255)),
                ('types_transact', Transactions.models.EnumField(choices=[('in', 'In'), ('out', 'Out')])),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.CustomUserModel')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.RemoveField(
            model_name='outcomingtransact',
            name='id_item',
        ),
        migrations.RemoveField(
            model_name='outcomingtransact',
            name='user',
        ),
        migrations.DeleteModel(
            name='InComingTransact',
        ),
        migrations.DeleteModel(
            name='OutComingTransact',
        ),
    ]
