# Generated by Django 2.2.5 on 2019-12-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customusermodel',
            table='Users',
        ),
    ]
