# Generated by Django 2.2.5 on 2019-12-21 14:14

import Items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit', Items.models.EnumField(choices=[('pcs', 'Pieces'), ('batang', 'Batang'), ('roll', 'Roll'), ('mtr', 'Meter'), ('set', 'Set')], default='pcs')),
                ('description', models.TextField(blank=True)),
                ('category', Items.models.EnumField(choices=[('kabel', 'Kabel'), ('pipa', 'Pipa'), ('valve', 'Valve'), ('mcb', 'MCB'), ('mccb', 'MCCB'), ('kabel', 'Kabel'), ('tee', 'Tee'), ('elbow', 'Elbow'), ('y', 'Pipa Sambungan Y'), ('flange core', 'Flange Core'), ('reducer', 'Reducer'), ('sock', 'Sock'), ('water mur', 'Water mur'), ('bushing', 'Bushing'), ('double naple', 'Double Naple'), ('dop', 'Dop'), ('co', 'Clean Out')], default='pipa')),
                ('classes', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
